highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://jekyller.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Suraj Sharma's Resume
name: Suraj Sharma
email: surajsharma1921@gmail.com
email_full: mailto:surajsharma1921@gmail.com
website: github.io/sustain
website_full: https://suraj192.github.io/vitae/
github: https://github.com/Suraj192
twitter: https://www.linkedin.com/in/suraj-sharma-a54060127/
tel: +358 442392352
tel_full: tel:+358 442392352 
google_maps: 'https://www.google.com/maps/place/Rasinkatu+10,+01360+Vantaa/@60.3230803,25.0651558,17z/data=!3m1!4b1!4m5!3m4!1s0x46920712027ab449:0xf5cf9d27fc410839!8m2!3d60.3230803!4d25.0651558'
address:
  street: Rasinkatu 10 D
  postcode: '01360' 
  city: Vantaa
  country: Finland
google_analytics: UA-00000000-1

# needed for travis-ci build
exclude: [vendor]
